# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-FR-SIRET
version:      0.01
version_from: lib/Business/FR/SIRET.pm
installdirs:  site
requires:
    Algorithm::LUHN:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
